# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4193c97aed72da51db148c879fce8c7ed3b11a20762e9923eed2594599a50310ca74defa426b6026f63ade5e3cba7c0da9154afa1ce2e687d4ce56b0ef590175

test:
  secret_key_base: 8b9b5ccbfdf4e10b609ca2a9b7742d4069783bbd53c5050612187c37d87b0a81181bc2bcc35032765744c0accd98f6a3babbb16ef27d8dc862529c726b64174b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
